name: CI

on:
  push:
    branches: [ "zig-pkg" ]
  pull_request:
    branches: [ "zig-pkg" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: zig build & run
        run: zig build -DPerf --summary all


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig fmt --check --ast-check **.zig
